// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO0Rk8wRPpqKHBerCgFoRNMfuP3p8pefU',
    appId: '1:1072741871117:web:90c539ddd471537259ef44',
    messagingSenderId: '1072741871117',
    projectId: 'eldermoodmirror-9599f',
    authDomain: 'eldermoodmirror-9599f.firebaseapp.com',
    storageBucket: 'eldermoodmirror-9599f.firebasestorage.app',
    measurementId: 'G-WFP093F97Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdTn4ZflRLo88ofYpUSOu_ZOWk_woqyro',
    appId: '1:1072741871117:android:592c1a7f831205b359ef44',
    messagingSenderId: '1072741871117',
    projectId: 'eldermoodmirror-9599f',
    storageBucket: 'eldermoodmirror-9599f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdVV9ewBdnKetNahdLIPISbrnzSoZuI7g',
    appId: '1:1072741871117:ios:7f56db9f3437f4a059ef44',
    messagingSenderId: '1072741871117',
    projectId: 'eldermoodmirror-9599f',
    storageBucket: 'eldermoodmirror-9599f.firebasestorage.app',
    iosBundleId: 'com.example.elderMoodMirror',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdVV9ewBdnKetNahdLIPISbrnzSoZuI7g',
    appId: '1:1072741871117:ios:7f56db9f3437f4a059ef44',
    messagingSenderId: '1072741871117',
    projectId: 'eldermoodmirror-9599f',
    storageBucket: 'eldermoodmirror-9599f.firebasestorage.app',
    iosBundleId: 'com.example.elderMoodMirror',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO0Rk8wRPpqKHBerCgFoRNMfuP3p8pefU',
    appId: '1:1072741871117:web:1060f3211a3d5d2459ef44',
    messagingSenderId: '1072741871117',
    projectId: 'eldermoodmirror-9599f',
    authDomain: 'eldermoodmirror-9599f.firebaseapp.com',
    storageBucket: 'eldermoodmirror-9599f.firebasestorage.app',
    measurementId: 'G-Y5LSZG3EMK',
  );
}
